web/router.ex
defmodule Ginjyo.Router do
  use Ginjyo.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Ginjyo.Plugs.AllowAccess, [:all]
    plug Ginjyo.Locale
  end

  pipeline :admin do
  #  plug Ginjyo.Plugs.AllowAccess, [:internal]
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/admin", Ginjyo do
    pipe_through :browser # Use the default browser stack
    #pipe_through :admin # Limit IP
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete
    resources "/users", UserController,  only: [:index, :new, :show, :update, :create, :edit]
    get "/users/:id/delete", UserController,  :delete
    get "/file", FileController, :index
    post "/file/upload", FileController, :file_upload
    resources "/roles", RoleController
    resources "/tags", TagController, only: [:index, :new, :show, :update, :create, :edit, :delete]
    resources "/articles", ArticleController, only: [:new, :create, :update, :edit, :delete]
  end

  scope "/", Ginjyo do
    pipe_through :browser # Use the default browser stack
    # public
    get "/", PageController, :index
    get "/tags/:id", ArticleController, :tagshow
    resources "/articles", ArticleController, only: [:index, :show]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Ginjyo do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Ginjyo.LayoutView do
  use Ginjyo.Web, :view

  def twitter_meta() do
    twitter = Application.get_env(:ginjyo, :twitter)
    if String.length(twitter) > 0 do
      "<meta name=\"twitter:card\" content=\"summary\"/>
      <meta name=\"twitter:site\" content=\"#{twitter}\"/>"
    end
  end

  def get_analytics() do
    code = Application.get_env(:ginjyo, :google_analytics)
    if String.length(code) > 0 do
      "<script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', '#{code}', 'auto');
        ga('send', 'pageview');
        </script>"
    end
  end
end

web/templates/layout/admin_header.html.eex
<div class="blog-masthead">
  <div class="container">
    <nav class="blog-nav">
      <a class="blog-nav-item title" href="<%= page_path(@conn, :index) %>">Ginjyo</a>
      <%= link "User", to: user_path(@conn, :index) , class: "blog-nav-item user" %>
      <li class="dropdown blog-nav-item article">
        <a href="#" class="dropdown-toggle article" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">
          Article
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu article">
          <li><%= link "List", to: article_path(@conn, :index) %></li>
          <li><%= link "Add", to: article_path(@conn, :new) %></li>
        </ul>
      </li>
      <%= link "File", to: file_path(@conn, :index), class: "blog-nav-item file" %>
      <%= link "Tag", to: tag_path(@conn, :index), class: "blog-nav-item tag" %>
      <%= if user = current_user(@conn) do %>
        <%= link "Log out", to: session_path(@conn, :delete), class: "blog-nav-item navbar-right label-danger" %>
      <% end %>
    </nav>
  </div>
</div>
<div class="container">
  <div class="blog-header">
    <div class="blog-title"><%= Application.get_env(:ginjyo, :site_title) %></div>
    <p><%= Application.get_env(:ginjyo, :description) %></p>
  </div>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="<%=Application.get_env(:ginjyo, :lang) %>">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="og:site_name" content="<%=Application.get_env(:ginjyo, :site_title) %>"/>
  <meta property="og:url" content="<%= Application.get_env(:ginjyo, :schema) <> @conn.host <> @conn.request_path %>" />
  <%= render_existing(@view_module, "meta." <> @view_template, assigns) ||
      render(Ginjyo.LayoutView, "meta.html", assigns) %>
  <%= raw(twitter_meta()) %>
  <%= raw(get_analytics()) %>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link href='http://fonts.googleapis.com/css?family=Montserrat:700,400' rel='stylesheet' type='text/css'>
<!-- Optional theme -->
<link rel="stylesheet" href="<%=static_path(@conn, "/css/app.css") %>">
</head>
<body>
  <%= if current_user(@conn) do %>
  <%= render "admin_header.html" , conn: @conn %>
  <%= else %>
  <%= render "header.html" , conn: @conn %>
  <%= end %>
    <div class="row">
      <%= if get_flash(@conn, :info) do %>
      <p class="alert alert-info" role="alert"><%= Gettext.gettext(Ginjyo.Gettext, get_flash(@conn, :info)) %></p>
      <%= end %>
      <%= if get_flash(@conn, :error) do %>
      <p class="alert alert-danger" role="alert"><%= Gettext.gettext(Ginjyo.Gettext, get_flash(@conn, :error)) %></p>
      <%= end %>
      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
  <script>
  $(function(){
    "use strict";
    var path = $(location).attr('pathname');
    if (path === '/') {
      $('a.blog-nav-item.title').addClass('active');
    } else if (path.match(/^\/articles\/?/) !== null) {
      $('a.blog-nav-item.article').addClass('active');
    }
  });
  </script>
  <%= if current_user(@conn) do %>
  <script>
  $(function(){
    "use strict";
    var path = $(location).attr('pathname');
    if (path.match(/^\/admin\/users\/?/) !== null) {
      $('a.blog-nav-item.user').addClass('active');
    } else if (path.match(/^(\/admin)?\/articles\/?/) !== null) {
      $('a.dropdown-toggle.article').addClass('active');
    } else if (path.match(/^\/admin\/file\/?/) !== null) {
      $('a.blog-nav-item.file').addClass('active');
    } else if (path.match(/^\/admin\/tag\/?/) !== null) {
      $('a.blog-nav-item.tag').addClass('active');
    }

    $('a.dropdown-toggle.article').on('click', function(e) {
      $('ul.dropdown-menu.article').show();
      e.stopPropagation();
    });

    $(document).on('click', function() {
      $('ul.dropdown-menu.article').hide();
    });

    $('ul.dropdown-menu.article').on('click', function(e) {
        e.stopPropagation();
    });

  });
  </script>
  <%= end %>
</body>
</html>

web/templates/layout/header.html.eex
<div class="blog-masthead">
  <div class="container">
    <nav class="blog-nav">
      <a class="blog-nav-item title" href="<%= page_path(@conn, :index) %>">Ginjyo</a>
      <%= link "Articles", to: article_path(@conn, :index), class: "blog-nav-item article" %>
    </nav>
  </div>
</div>
<div class="container">
  <div class="blog-header">
    <div class="blog-title"><%= Application.get_env(:ginjyo, :site_title) %></div>
    <p><%= Application.get_env(:ginjyo, :description) %></p>
  </div>

web/templates/layout/meta.html.eex
<meta property="og:type" content="blog"/>
<meta property="og:image" content="<%= static_path(@conn, Application.get_env(:ginjyo, :site_image))%>" />
<meta property="og:title" content="<%= Application.get_env(:ginjyo, :site_title) %>"/>
<meta property="og:description" content="<%= Application.get_env(:ginjyo, :description) %>" />
<title><%= Application.get_env(:ginjyo, :site_title) %></title>